### ISSUE TITLE
Exception in thread "main" org.json.JSONException: A JSONObject text must begin with '{' at 0 [character 1 line 1]

### ISSUE THREAD

**Issue by GreenArrowlol** [myne145/Youtube-Notification-Discord-Bot#1]
java -Dterminal.jline=false -Dterminal.ansi=true -jar Youtube_Bot.jar
Exception in thread "main" org.json.JSONException: A JSONObject text must begin with '{' at 0 [character 1 line 1]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:497)
        at org.json.JSONObject.<init>(JSONObject.java:208)
        at org.json.JSONObject.<init>(JSONObject.java:404)
        at com.myne145.ytdiscordbot.config.BotConfig.createConfig(BotConfig.java:60)
        at com.myne145.ytdiscordbot.Bot.main(Bot.java:138)

**Comment by antoni-kuczynski** [comment]
This can happen when the config file is empty / filled incorrectly.
[Proper config file example here](https://github.com/myne145/Youtube-Notification-Discord-Bot#local)

**Comment by GreenArrowlol** [comment]
> This can happen when the config file is empty / filled incorrectly. [Proper config file example here](https://github.com/myne145/Youtube-Notification-Discord-Bot#local)

That happened on the first startup, I ran it for the first time and that showed up and the config looked empty too. Please check it once.

**Comment by GreenArrowlol** [comment]
Oh wait we're supposed to fill in?

**Comment by antoni-kuczynski** [comment]
Yeah, look at README.MD for instructions, ik the format's bad, I'm working on setting these values up through discord commands.
